version: '3'

# silent: true

env:
  ROOT_PROJECT: ./etl
  DOCKER: docker-compose.yaml

tasks:
  pre_project:
    cmds:
      - echo "CREATE THE AIRLFOW AND THE STORAGE DIRS"  
      - echo "AIRFLOW_UID=$(id -u)" > $ROOT_PROJECT/.env  
      - |  
        {  
          echo "REDSHIFT_URL="  
          echo "REDSHIFT_USER="  
          echo "REDSHIFT_PWD="  
          echo "REDSHIFT_PORT="  
          echo "REDSHIFT_DB="  
          echo "REDSHIFT_SCHEMA="  
          echo "EMAIL="  
          echo "EMAIL_PASSWORD="  
          echo "SMTP_HOST="  
          echo "SMTP_STARTTLS="  
          echo "SMTP_SSL="  
          echo "SMTP_USER="  
          echo "SMTP_PASSWORD="  
          echo "SMTP_PORT="  
          echo "SMTP_MAIL_FROM="  
        } >> $ROOT_PROJECT/.env  
      - mkdir -p $ROOT_PROJECT/{raw_data,processed_data,dags,logs,plugins,config}  
      - tree -L 2 $ROOT_PROJECT 

  start_project:
      - docker compose -f $ROOT_PROJECT/$DOCKER up airflow-init --build
      - docker compose -f $ROOT_PROJECT/$DOCKER up -d --build
      - docker container ls -a

  down_project:
      - docker compose -f $ROOT_PROJECT/$DOCKER down

  cleanup: 
    cmds:
      - rm -rf  $ROOT_PROJECT/{raw_data,processed_data,logs,plugins,config}
      - rm -f   $ROOT_PROJECT/.env
      - rm -rf  $ROOT_PROJECT/dags/*pycache*
      - rm -rf  $ROOT_PROJECT/dags/*/*pycache*